runtime: python27
api_version: 1
threadsafe: yes

instance_class: F4_1G
automatic_scaling:
  min_idle_instances: 2
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 40

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap
  http_headers:
    Access-Control-Allow-Origin: "*"
  

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: MySQLdb
  version: "latest"

- name: PIL
  version: "1.1.7"

- name: ssl
  version: 2.7.11

builtins:
- remote_api: on

env_variables:
   GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'
   CLOUDSQL_CONNECTION_NAME: 'devnpfieldapp:us-west1:devcloudsql'
   CLOUDSQL_USER: 'root'
   CLOUDSQL_PASSWORD: 'NDEelLmxwKb7Aijk'
    
